name: Build Shamrock APK

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
      - '**.txt'
      - '.github/**'
      - '.idea/**'
      - '!.github/workflows/**'

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 17
          cache: 'gradle'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: 12266719
          accept-android-sdk-licenses: true
          log-accepted-android-sdk-licenses: true
          packages: |
            platforms;android-34
            build-tools;34.0.0
            cmake;3.22.1
            tools
            platform-tools

      - name: Accept all licenses explicitly
        run: |
          export ANDROID_SDK_ROOT=${ANDROID_SDK_ROOT:-$ANDROID_HOME}
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses || true
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --update || true
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties

      - name: Verify environment
        run: |
          echo "ANDROID_HOME=$ANDROID_HOME"
          echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT"
          echo "JAVA_HOME=$JAVA_HOME"
          ls -la $ANDROID_SDK_ROOT/cmdline-tools || true

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Build with Gradle
        run: |
          echo ${{ secrets.SIGN_KEYSTORE_BASE64 }} | base64 -d > app/keystore.jks
          chmod +x ./gradlew
          ./gradlew :app:assembleRelease --build-cache --parallel --daemon --warning-mode all --stacktrace
          echo "APK_FILE_ALL=app/build/outputs/apk/app/release/*.apk" >> $GITHUB_ENV
          echo "APK_FILE_ARM64=app/build/outputs/apk/arm64/release/*.apk" >> $GITHUB_ENV
          echo "APK_FILE_X86_64=app/build/outputs/apk/x64/release/*.apk" >> $GITHUB_ENV
        env:
          KEYSTORE_PATH: "app/keystore.jks"
          KEYSTORE_PASSWORD: ${{ secrets.SIGN_KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.SIGN_ALIAS }}
          KEY_PASSWORD: ${{ secrets.SIGN_KEY_PASSWORD }}

      - name: Install aapt
        run: sudo apt-get update && sudo apt-get install -y aapt

      - name: Set Shamrock Version
        run: |
          apk_file=$(ls app/build/outputs/apk/app/release/*.apk | head -1)
          apk_dump=$(aapt dump badging "$apk_file")
          version_name=$(sed -n "s/.*versionName='\([^']*\)'.*/\1/p" <<< "$apk_dump")
          echo "SHAMROCK_VERSION=$version_name" >> $GITHUB_ENV

      - name: Show Artifacts SHA256
        run: |
          echo "### Build Success :rocket:" >> $GITHUB_STEP_SUMMARY
          echo "|ABI|SHA256|" >> $GITHUB_STEP_SUMMARY
          echo "|:--------:|:----------|" >> $GITHUB_STEP_SUMMARY
          for apk in ${{ env.APK_FILE_ALL }}
          do
            all=($(sha256sum $apk))
            echo "|all|$all" >> $GITHUB_STEP_SUMMARY
          done
          for apk in ${{ env.APK_FILE_ARM64 }}
          do
            arm64=($(sha256sum $apk))
            echo "|arm64|$arm64" >> $GITHUB_STEP_SUMMARY
          done
          for apk in ${{ env.APK_FILE_X86_64 }}
          do
            x64=($(sha256sum $apk))
            echo "|x64|$x64" >> $GITHUB_STEP_SUMMARY
          done

      - name: Upload APK All
        uses: actions/upload-artifact@v4
        with:
          name: shamrock-${{ env.SHAMROCK_VERSION }}-all
          path: ${{ env.APK_FILE_ALL }}

      - name: Upload APK ARM64
        uses: actions/upload-artifact@v4
        with:
          name: shamrock-${{ env.SHAMROCK_VERSION }}-arm64
          path: ${{ env.APK_FILE_ARM64 }}

      - name: Upload APK X86_64
        uses: actions/upload-artifact@v4
        with:
          name: shamrock-${{ env.SHAMROCK_VERSION }}-x64
          path: ${{ env.APK_FILE_X86_64 }}

      - name: Create Release
        if: github.ref == 'refs/heads/master'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.SHAMROCK_VERSION }}
          name: Shamrock v${{ env.SHAMROCK_VERSION }}
          body: |
            自动构建的Shamrock APK
            
            版本: ${{ env.SHAMROCK_VERSION }}
            构建时间: ${{ github.run_number }}
            
            ### 下载说明
            - **all**: 通用版本，支持所有架构
            - **arm64**: ARM64架构专用（推荐现代手机使用）
            - **x64**: x86_64架构专用
          files: |
            ${{ env.APK_FILE_ALL }}
            ${{ env.APK_FILE_ARM64 }}
            ${{ env.APK_FILE_X86_64 }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
