name: Build Shamrock APK

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
      - '**.txt'
      - '.github/**'
      - '.idea/**'
      - '!.github/workflows/**'

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4


      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 17
          cache: 'gradle'

      - name: Setup cmake
        run: |
          echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "cmake;3.22.1" --sdk_root=${ANDROID_SDK_ROOT} &> /dev/null
          echo "sdk.dir=${ANDROID_HOME}" > local.properties


      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Build with Gradle
        run: |

          echo ${{ secrets.SIGN_KEYSTORE_BASE64 }} | base64 -d > app/keystore.jks
          chmod +x ./gradlew

          ./gradlew :app:assembleRelease --build-cache --parallel --daemon --warning-mode all --stacktrace

          echo "APK_FILE_ALL=app/build/outputs/apk/app/release/*.apk" >> $GITHUB_ENV
          echo "APK_FILE_ARM64=app/build/outputs/apk/arm64/release/*.apk" >> $GITHUB_ENV
          echo "APK_FILE_X86_64=app/build/outputs/apk/x64/release/*.apk" >> $GITHUB_ENV
        env:

          KEYSTORE_PATH: "app/keystore.jks"
          KEYSTORE_PASSWORD: ${{ secrets.SIGN_KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.SIGN_ALIAS }}
          KEY_PASSWORD: ${{ secrets.SIGN_KEY_PASSWORD }}

      - name: Install aapt
        run: sudo apt-get update && sudo apt-get install -y aapt

      - name: Set Shamrock Version
        run: |

          apk_file=$(ls app/build/outputs/apk/app/release/*.apk | head -1)
          apk_dump=$(aapt dump badging "$apk_file")
          version_name=$(sed -n "s/.*versionName='\([^']*\)'.*/\1/p" <<< "$apk_dump")
          echo "SHAMROCK_VERSION=$version_name" >> $GITHUB_ENV

      - name: Show Artifacts SHA256
        run: |
          echo "### Build Success :rocket:" >> $GITHUB_STEP_SUMMARY
          echo "|ABI|SHA256|" >> $GITHUB_STEP_SUMMARY
          echo "|:--------:|:----------|" >> $GITHUB_STEP_SUMMARY

          for apk in ${{ env.APK_FILE_ALL }}
          do
            all=($(sha256sum $apk))
            echo "|all|$all" >> $GITHUB_STEP_SUMMARY
          done
          
          for apk in ${{ env.APK_FILE_ARM64 }}
          do
            arm64=($(sha256sum $apk))
            echo "|arm64|$arm64" >> $GITHUB_STEP_SUMMARY
          done
          
          for apk in ${{ env.APK_FILE_X86_64 }}
          do
            x86_64=($(sha256sum $apk))
            echo "|x86_64|$x86_64" >> $GITHUB_STEP_SUMMARY
          done

      - name: Upload ALL APK RELEASE
        uses: actions/upload-artifact@v4
        with:
          name: Shamrock-v${{ env.SHAMROCK_VERSION }}-all
          path: ${{ env.APK_FILE_ALL }}

      - name: Upload ARM64 APK RELEASE
        uses: actions/upload-artifact@v4
        with:
          name: Shamrock-v${{ env.SHAMROCK_VERSION }}-arm64
          path: ${{ env.APK_FILE_ARM64 }}

      - name: Upload X86_64 APK RELEASE
        uses: actions/upload-artifact@v4
        with:
          name: Shamrock-v${{ env.SHAMROCK_VERSION }}-x86_64
          path: ${{ env.APK_FILE_X86_64 }}
